package id.idprogramming.simplemovie.model

fun getListMovie(): List<Movie> = listOf(
    Movie(
        genreIds = listOf(
            878,
            28,
            53,
        ),
        id = 670292,
        overview = "mid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
        popularity = 965.179,
        posterPath = "https://image.tmdb.org/t/p/w500/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
        releaseDate = "2023-09-27",
        title = "The Creator",
        voteAverage = 7.206,
        voteCount = 995,
    ),
    Movie(
        genreIds = listOf(
            7,
            9648,
        ),
        id = 507089,
        overview = "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
        popularity = 1208.697,
        posterPath = "https://image.tmdb.org/t/p/w500/j9mH1pr3IahtraTWxVEMANmPSGR.jpg",
        releaseDate = "2023-10-25",
        title = "Five Nights at Freddy's",
        voteAverage = 7.901,
        voteCount = 2418,
    ),
    Movie(
        genreIds = listOf(
            28,
            12,
            53,
        ),
        id = 299054,
        overview = "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
        popularity = 923.353,
        posterPath = "https://image.tmdb.org/t/p/w500/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg",
        releaseDate = "2023-09-15",
        title = "Expend4bles",
        voteAverage = 6.41,
        voteCount = 773,
    ),
    Movie(
        genreIds = listOf(
            16,
            10751,
            10402,
            14,
            35,
        ),
        id = 901362,
        overview = "When Branch’s brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
        popularity = 853.007,
        posterPath = "https://image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
        releaseDate = "2023-10-12",
        title = "Trolls Band Together",
        voteAverage = 6.484,
        voteCount = 61,
    ),
    Movie(
        genreIds = listOf(
            8,
            12,
            878,
        ),
        id = 695721,
        overview = "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
        popularity = 676.866,
        posterPath = "https://image.tmdb.org/t/p/w500/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
        releaseDate = "2023-11-15",
        title = "The Hunger Games: The Ballad of Songbirds & Snakes",
        voteAverage = 7.25,
        voteCount = 308,
    ),
    Movie(
        genreIds = listOf(
            7,
            9648,
            53,
        ),
        id = 841742,
        overview = "Felix and Martha, the two offspring of legendary serial murderer The Skinner of Mons, grapple with the grotesque legacy bequeathed to them. While Martha works a menial janitorial job, Felix continues his father's reign of terror. But following a brutal attack at work, Martha quickly descends into madness, finding she must come to terms with the infamous blood that flows through her veins.",
        popularity = 536.791,
        posterPath = "https://image.tmdb.org/t/p/w500/8HKjrjwTjvDscC9uZNk6dCRHcfd.jpg",
        releaseDate = "2023-09-08",
        title = "Megalomaniac",
        voteAverage = 6.2,
        voteCount = 13,
    ),
    Movie(
        genreIds = listOf(
            27,
            53,
        ),
        id = 951491,
        overview = "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
        popularity = 532.5,
        posterPath = "https://image.tmdb.org/t/p/w500/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg",
        releaseDate = "2023-09-26",
        title = "Saw X",
        voteAverage = 7.411,
        voteCount = 1110,
    ),
    Movie(
        genreIds = listOf(
            28,
            12,
            878,
            35,
        ),
        id = 609681,
        overview = "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
        popularity = 526.929,
        posterPath = "https://image.tmdb.org/t/p/w500/y4YMYsGSMwu8e985g0Zbumvqxld.jpg",
        releaseDate = "2023-11-08",
        title = "The Marvels",
        voteAverage = 6.52,
        voteCount = 499,
    ),
    Movie(
        genreIds = listOf(
            28,
            18,
        ),
        id = 678512,
        overview = "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
        popularity = 493.853,
        posterPath = "https://image.tmdb.org/t/p/w500/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
        releaseDate = "2023-07-03",
        title = "Sound of Freedom",
        voteAverage = 8.093,
        voteCount = 1491,
    ),
    Movie(
        genreIds = listOf(
            28,
            53,
            80,
        ),
        id = 762430,
        overview = "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks- all with his kids trapped in the back seat.",
        popularity = 448.195,
        posterPath = "https://image.tmdb.org/t/p/w500/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg",
        releaseDate = "2023-08-23",
        title = "Retribution",
        voteAverage = 6.991,
        voteCount = 678,
    ),
)

fun getListGenre(): List<Genre> = listOf(
    Genre(28, "Action"),
    Genre(12, "Adventure"),
    Genre(16, "Animation"),
    Genre(35, "Comedy"),
    Genre(80, "Crime"),
    Genre(99, "Documentary"),
    Genre(18, "Drama"),
    Genre(10751, "Family"),
    Genre(14, "Fantasy"),
    Genre(36, "History"),
    Genre(27, "Horror"),
    Genre(10402, "Music"),
    Genre(9648, "Mystery"),
    Genre(10749, "Romance"),
    Genre(878, "Science Fiction"),
    Genre(10770, "TV Movie"),
    Genre(53, "Thriller"),
    Genre(10752, "War"),
    Genre(37, "Western"),
)
